name: Build and Push Docker Image

# The actions will be triggered when there
# is a push to the main branch.
on:
  push: 
    tags:
      - 'v*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Action to check out code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Action to set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Action to log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Docker Metadata action
        uses: docker/metadata-action@v5.9.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/project3 #FIXED
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
        
          # Action to build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Project4/dockerfile
          push: true
          #tags: ${{ secrets.DOCKER_USERNAME }}/project3:latest
          tags: ${{ steps.meta.outputs.tags }}
